"use client";
import { useEffect, useState, type FormEvent } from "react";

type Slot = { id: string; startsAt: string; endsAt: string; appointmentType: string; mentorName: string; mentorTitle: string };
type Appointment = { id: string; title: string; notes: string | null; startsAt: string; endsAt: string; status: string; meetUrl: string | null; mentor: string };
export function AppointmentBooking() {
  const [slots, setSlots] = useState<Slot[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [slotId, setSlotId] = useState("");
  const [title, setTitle] = useState("");
  const [notes, setNotes] = useState("");
  const [status, setStatus] = useState("Loading the open hours…");
  async function refresh() { const response = await fetch("/api/appointments"); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setSlots(payload.slots); setAppointments(payload.appointments); setStatus(payload.slots.length ? "Choose a time for a thoughtful conversation." : "No mentor has published an open time yet."); }
  useEffect(() => { void refresh().catch((error: unknown) => setStatus(error instanceof Error ? error.message : "Mentor availability could not be loaded.")); }, []);
  async function request(event: FormEvent) { event.preventDefault(); setStatus("Sending your request to the mentor…"); try { const response = await fetch("/api/appointments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slotId, title, notes }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setStatus(payload.message); setSlotId(""); setTitle(""); setNotes(""); await refresh(); } catch (error) { setStatus(error instanceof Error ? error.message : "Your request could not be sent."); } }
  async function cancel(id: string) { try { const response = await fetch(`/api/appointments/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "CANCELLED" }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setStatus(payload.message); await refresh(); } catch (error) { setStatus(error instanceof Error ? error.message : "This request could not be changed."); } }
  return <><p className="platform-message" role="status">{status}</p>{slots.length > 0 && <form className="platform-card platform-form" onSubmit={request}><label>Choose a mentor and time<select value={slotId} onChange={(event) => setSlotId(event.target.value)} required><option value="">Select an opening</option>{slots.map((slot) => <option value={slot.id} key={slot.id}>{slot.mentorName} · {slot.mentorTitle} · {new Date(slot.startsAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST · {slot.appointmentType}</option>)}</select></label><label>What would you like to talk about?<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={180} minLength={4} required placeholder="A project, a problem, a next step…" /></label><label>A little context<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={2000} rows={4} /></label><button className="platform-button" disabled={!slotId}>Request the conversation ↗</button></form>}{appointments.map((appointment) => <article className="platform-card" key={appointment.id}><p className="platform-eyebrow">{appointment.status} · {appointment.mentor}</p><h2>{appointment.title}</h2><p>{new Date(appointment.startsAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>{appointment.meetUrl && <a className="platform-button" href={appointment.meetUrl} target="_blank" rel="noreferrer">Join the conversation ↗</a>}{!['CANCELLED','COMPLETED','NO_SHOW'].includes(appointment.status) && <button className="platform-button" onClick={() => void cancel(appointment.id)}>Cancel request</button>}</article>)}</>;
}
